name: Zenwebvideo
favicon: null
layout_spectrum: 0.25121
typography_spectrum: 0.36353
title: The video site for your needs
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cecbb6'
    - '#1d1815'
    - '#453527'
    - '#7e7967'
    - '#a3a691'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
