name: Zenwebvideo
favicon: null
layout_spectrum: 0.23172
typography_spectrum: 0.3379
title: The video site for your needs
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b3c7e2'
    - '#21141b'
    - '#4b4d62'
    - '#dee8f4'
    - '#7b99b3'
  brandStrength: 0.3125
  lightness: 0.4375
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
